route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
  receiver: telegram

  routes:
    - matchers:
        - notify="telegram"
      receiver: telegram

inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    equal: [alertname]

receivers:
  - name: "telegram"
    webhook_configs:
      - url: "http://192.168.1.4:9087/alert/-809124010"
        send_resolved: true
